version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    env_file:
      - .env

  app:
    build: ./app
    restart: always
    entrypoint: ./entrypoint.dev.sh
    command: '"tail -f /dev/null"'
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - NODE_ENV=development