version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db
    env_file:
      - .env

  app:
    build: ./app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env